.github/workflows/main.yml, py14/tests/test_transpiler.py, py14/transpiler.py, py2many/clike.py, py2many/context.py, py2many/inference.py, py2many/scope.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/tests/test_tracer.py, pyrs/transpiler.py
Sits on top of https://github.com/adsharma/py2many/pull/48
but that is optional - I can rebase onto main if pr 48
is not desirable or needs adjustments.
=> ci: Add black & pyflakes

pygo/transpiler.py, pykt/transpiler.py, tests/expected/binit.kt, tests/test_cli.py
Also fixup the hack in pygo
Partially Fixes: https://github.com/adsharma/py2many/issues/28
=> kotlin: handle list.append() correctly

.github/workflows/main.yml, tests/test_cli.py
Closes https://github.com/adsharma/py2many/issues/55
=> ci: Install more CI dependencies

pydart/transpiler.py, pygo/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/cases/hello_world.py, tests/expected/hello_world.cpp, tests/expected/hello_world.dart, tests/expected/hello_world.go, tests/expected/hello_world.kt, tests/expected/hello_world.nim, tests/expected/hello_world.rs, tests/expected/print.dart, tests/expected/print.go, tests/expected/print.nim, tests/expected/print.rs, tests/test_cli.py, tox.ini
Extra infrastructure for https://github.com/adsharma/py2many/issues/25 , for when asserts are not ideal.
tox.ini changes are to workaround https://github.com/pytest-dev/pytest-cov/issues/168
=> Add compatable hello world test case

pynim/clike.py
tested via:
```
def main():
pass
```
=> nim: use discard for ast.pass

py2many/context.py
Was found by running the test case linked to
https://github.com/adsharma/py2many/issues/88
=> analysis: add a defensive check

.github/workflows/main.yml, py14/tests/test_transpiler.py, py14/transpiler.py, py2many/cli.py, tests/cases/infer_ops.py, tests/expected/assert.cpp, tests/expected/binit.cpp, tests/expected/fib.cpp, tests/expected/hello_world.cpp, tests/expected/infer_ops.cpp, tests/expected/infer_ops.dart, tests/expected/infer_ops.go, tests/expected/infer_ops.jl, tests/expected/infer_ops.kt, tests/expected/infer_ops.nim, tests/expected/infer_ops.rs, tests/expected/int_enum.cpp, tests/expected/lambda.cpp, tests/expected/print.cpp, tests/expected/rect.cpp, tests/test_cli.py
Sits on top of https://github.com/adsharma/py2many/pull/60
=> ci: Add julia and formatter on macOS and Linux 

.github/workflows/main.yml, py14/transpiler.py, py2many/inference.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, tests/cases/coverage.py, tests/expected/binit.go, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs, tests/test_cli.py
Mainly fixes the python `range` functionality across languages
=> Improve test coverage

py2many/analysis.py, py2many/inference.py, pydart/transpiler.py, pyrs/transpiler.py, tests/cases/global2.py, tests/expected/global2.dart, tests/expected/global2.rs, tests/expected/int_enum.rs, tests/expected/str_enum.rs
rust now support set and dict globals.
dart already supported them.
=> pyrs: Use lazy_static for set and dict globals

py14/transpiler.py, py2many/annotation_transformer.py, py2many/context.py, py2many/inference.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/cases/coverage.py, tests/expected/binit.jl, tests/expected/binit.nim, tests/expected/binit.rs, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs
Only the changes to pyjl were the main intent of the change. The rest are bug fixes to get coverage.py to pass.
=> julia: fix array indexing logic

py2many/analysis.py, py2many/context.py, py2many/inference.py, pyrs/transpiler.py, tests/expected/rect.rs, tests/test_cli.py
Related to https://github.com/adsharma/py2many/issues/65
=> rust: handle struct literals correctly

py14/transpiler.py, pyjl/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/cases/lambda.py, tests/expected/lambda.cpp, tests/expected/lambda.dart, tests/expected/lambda.go, tests/expected/lambda.jl, tests/expected/lambda.kt, tests/expected/lambda.nim, tests/expected/lambda.rs, tests/test_cli.py
Needs better type inference of args
Fixes https://github.com/adsharma/py2many/issues/15
Fixes https://github.com/adsharma/py2many/issues/27
=> lambda: fix rust, nim and julia

py14/clike.py, py14/tests/test_transpiler.py, py14/transpiler.py, tests/expected/binit.cpp, tests/expected/bubble_sort.cpp, tests/expected/comb_sort.cpp, tests/expected/coverage.cpp, tests/expected/global.cpp, tests/expected/global2.cpp, tests/expected/int_enum.cpp, tests/test_cli.py
There are no string enums in C++. Perhaps use a normal class?
Also fixes list, set and map literals
=> cpp: Fix int_enums

py14/clike.py, py2many/cli.py, py2many/clike.py, pydart/transpiler.py, pygo/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/cases/coverage.py, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs
Fixes https://github.com/adsharma/py2many/issues/77
=> py2many: Fix is None checking

pyrs/transpiler.py, tests/cases/int_enum.py, tests/expected/int_enum.cpp, tests/expected/int_enum.dart, tests/expected/int_enum.go, tests/expected/int_enum.jl, tests/expected/int_enum.kt, tests/expected/int_enum.nim, tests/expected/int_enum.rs
Fixes https://github.com/adsharma/py2many/issues/18
=> rust: remove warnings from int_enum.rs

pyjl/transpiler.py, tests/expected/binit.jl, tests/expected/comb_sort.jl, tests/expected/infer_ops.jl, tests/test_cli.py
Fixes https://github.com/adsharma/py2many/issues/78
Fixes https://github.com/adsharma/py2many/issues/80
=> julia: add casts and converts types where necessary

py2many/cli.py, py2many/rewriters.py
https://github.com/adsharma/py2many/issues/30
=> py2many: fix duplicate main

py2many/annotation_transformer.py, py2many/cli.py, py2many/clike.py, py2many/inference.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/clike.py, pykt/transpiler.py, pynim/transpiler.py, tests/cases/lambda.py, tests/expected/bubble_sort.kt, tests/expected/bubble_sort.nim, tests/expected/comb_sort.kt, tests/expected/comb_sort.nim, tests/expected/global2.kt, tests/expected/global2.nim, tests/expected/int_enum.kt, tests/expected/lambda.kt, tests/expected/str_enum.kt, tests/expected/str_enum.nim, tests/test_cli.py
Only one failure left - infer_ops.
=> Kotlin tests

.github/workflows/main.yml, py14/transpiler.py, py2many/clike.py, py2many/rewriters.py, pydart/transpiler.py, pykt/transpiler.py, tests/expected/binit.dart, tests/expected/bubble_sort.dart, tests/expected/comb_sort.dart, tests/expected/coverage.dart, tests/expected/fib.dart, tests/expected/global.dart, tests/expected/global2.dart, tests/expected/infer.dart, tests/expected/infer_ops.dart, tests/expected/int_enum.dart, tests/expected/print.dart
=> Dart tests

py2many/cli.py, pygo/clike.py, pygo/inference.py, pygo/transpiler.py, pyrs/clike.py, tests/expected/bubble_sort.go, tests/expected/infer_ops.go
=> go: fix some tests

.github/workflows/main.yml, py2many/clike.py, pygo/clike.py, pygo/runtime/go.mod, pygo/runtime/pygo.go, pygo/transpiler.py, tests/expected/global.go, tests/expected/global2.go, tests/expected/int_enum.go, tests/test_cli.py
=> Go contains

.github/workflows/main.yml, pydart/transpiler.py, tests/expected/int_enum.dart, tests/expected/str_enum.dart, tests/test_cli.py
State of Enums in Dart (2021)
https://cloud-trends.medium.com/advanced-enums-in-flutter-a8f2e2702ffd
Fixes https://github.com/adsharma/py2many/issues/41
=> dart: support enums

tests/cases/coverage.py, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs
Uncomment lines that were previously commented out
beause of missing/incomplete functionality
=> py2many: increase test coverage

py2many/clike.py, py2many/inference.py, pygo/clike.py, pygo/inference.py, pygo/transpiler.py, tests/cases/infer_ops.py, tests/expected/comb_sort.go, tests/expected/infer_ops.cpp, tests/expected/infer_ops.dart, tests/expected/infer_ops.go, tests/expected/infer_ops.jl, tests/expected/infer_ops.kt, tests/expected/infer_ops.nim, tests/expected/infer_ops.rs, tests/expected/int_enum.cpp, tests/expected/int_enum.dart, tests/expected/int_enum.go, tests/expected/int_enum.rs, tests/expected/lambda.go, tests/expected/str_enum.dart, tests/expected/str_enum.rs, tests/test_cli.py
Only str_enum remains unimplemented
=> Go test fixes

py2many/cli.py, pynim/clike.py, pynim/inference.py, pynim/transpiler.py, tests/expected/infer_ops.nim, tests/test_cli.py
Fixes https://github.com/adsharma/py2many/issues/16
=> nim: fix infer_ops.py case

py14/transpiler.py, pynim/inference.py, pyrs/inference.py, pyrs/transpiler.py, tests/expected/comb_sort.nim, tests/expected/comb_sort.rs, tests/expected/coverage.nim, tests/expected/coverage.rs, tests/expected/infer_ops.nim, tests/expected/infer_ops.rs, tests/expected/print.nim, tests/expected/print.rs
Also a couple of other fixes to transpile langcomp's test_python.py
=> float: python floats are double precision

.github/workflows/main.yml, py2many/cli.py, tests/test_cli.py
Sits on top of https://github.com/adsharma/py2many/pull/186
=> CI: Fix golint

py2many/inference.py, pydart/clike.py, pydart/transpiler.py, tests/cases/exceptions.py, tests/expected/binit.dart, tests/expected/exceptions.dart, tests/expected/infer_ops.dart, tests/test_cli.py
Other languages which support exceptions can replicate this.
=> dart: implement exceptions

py2many/cli.py, py2many/rewriters.py, pygo/transpiler.py, tests/expected/assert.go, tests/expected/binit.go, tests/expected/bubble_sort.go, tests/expected/comb_sort.go, tests/expected/coverage.go, tests/expected/fib.go, tests/expected/global.go, tests/expected/global2.go, tests/expected/infer.go, tests/expected/infer_ops.go, tests/expected/int_enum.go, tests/expected/lambda.go, tests/expected/print.go, tests/expected/rect.go, tests/expected/str_enum.go
This affects symbol visibility.
Fixes: https://github.com/adsharma/py2many/issues/174
Related to: https://github.com/adsharma/py2many/issues/191
=> go: Use GoNames in tests

py2many/cli.py, py2many/clike.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/cases/coverage.py, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs
Fixes: https://github.com/adsharma/py2many/issues/210
=> ifexp: implement for languages other than rust

py2many/cli.py, py2many/clike.py, py2many/rewriters.py, tests/cases/print.py, tests/expected/coverage.cpp, tests/expected/print.cpp, tests/expected/print.dart, tests/expected/print.go, tests/expected/print.jl, tests/expected/print.kt, tests/expected/print.nim, tests/expected/print.rs
To improve coverage and take advantage of recent work
=> print: add a print bool test

py2many/clike.py, py2many/context.py, pycpp/transpiler.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py
These will be used to resolve types in the future.
Fix bugs due to lost Import nodes.
=> imports: remember aliases

.github/workflows/main.yml, pycpp/clike.py, pycpp/transpiler.py, tests/expected/assert.cpp, tests/expected/binit.cpp, tests/expected/bitops.cpp, tests/expected/bubble_sort.cpp, tests/expected/comb_sort.cpp, tests/expected/coverage.cpp, tests/expected/fib.cpp, tests/expected/global.cpp, tests/expected/global2.cpp, tests/expected/hello_world.cpp, tests/expected/infer.cpp, tests/expected/infer_ops.cpp, tests/expected/int_enum.cpp, tests/expected/lambda.cpp, tests/expected/nested_dict.cpp, tests/expected/print.cpp, tests/expected/rect.cpp, tests/expected/str_enum.cpp, tests/test_cli.py
std includes should be sorted and de-duped.
=> pycpp: Use Google style and cpplint

py2many/cli.py, tests/test_cli.py
Fixes https://github.com/adsharma/py2many/issues/244
=> cli: Fix exit code

pyjl/transpiler.py, pyrs/transpiler.py, tests/cases/dict.py, tests/expected/dict.jl, tests/expected/dict.rs, tests/test_unsupported.py
Related to https://github.com/adsharma/py2many/issues/248
=> dict .keys() and .values()

py2many/inference.py, tests/test_unsupported.py
This is so that we can catch problems at source and report
the lineno instead of relying on the compiler for the target
a1: i8 = 300   # type error, bit lengths don't match
a: i8 = 10     # ok
b: i16 = 300   # ok
c: i16 = a + b # type error due to potential overflow
=> py2many: implement support for checking fixed width types

pyrs/plugins.py
Fixes https://github.com/adsharma/py2many/issues/264
=> pyrs: Fix tempfile import

py2many/cli.py
This can be used by a web based UI to the transpiler
=> cli: add process_once_data

pydart/transpiler.py, tests/cases/generator.py, tests/cases/sys_argv.py, tests/expected/binit.dart, tests/expected/bitops.dart, tests/expected/bubble_sort.dart, tests/expected/comb_sort.dart, tests/expected/sys_argv.cpp, tests/expected/sys_argv.dart, tests/expected/sys_argv.go, tests/expected/sys_argv.jl, tests/expected/sys_argv.kt, tests/expected/sys_argv.nim, tests/expected/sys_argv.rs, tests/test_cli.py
Fixes https://github.com/adsharma/py2many/issues/280
=> tests: Invoke dart with assertions enabled

tests/test_unsupported.py
The snippets were not being checked for SyntaxError's
for some languages.
=> test_unsupported: Fix Python runner

.github/workflows/main.yml, py2many/cli.py, py2many/clike.py, pycpp/transpiler.py, pyjl/transpiler.py, pynim/transpiler.py, setup.py, tests/cases/byte_literals.py, tests/test_cli.py, tests/test_transpile_self.py
Simplify a raise in cli.py to avoid tripping up
transpilers.
Raise `NotImplementedError` in py2many to avoid
suppressing `Exception`.
=> transpile self: Add more languages

py2many/context.py
Fixes: https://github.com/adsharma/py2many/issues/302
=> analysis: check if the variable is None

py2many/clike.py, py2many/tracer.py, pycpp/plugins.py, pycpp/transpiler.py
Related to: https://github.com/adsharma/py2many/issues/302
=> cpp: use plugins for math

Cargo.toml, py2many/analysis.py, pyrs/transpiler.py, tests/cases/sealed.py, tests/expected/sealed.rs, tox.ini
=> rust: support for sealed classes

py2many/clike.py, pyrs/plugins.py, pyrs/transpiler.py
Fixes: https://github.com/adsharma/py2many/issues/303
=> rust: implement support for math/time/random lib calls

py2many/analysis.py, py2many/clike.py, py2many/result.py, pyjl/transpiler.py, pyrs/transpiler.py, tests/test_transpile_self.py
Fixes https://github.com/adsharma/py2many/issues/322
=> py2many: add a Result type

.github/workflows/main.yml, .gitignore, py2many/cli.py, tests/test_cli.py, tests/test_unsupported.py
This problem was raised in https://github.com/adsharma/py2many/issues/311#issuecomment-853484870
=> tests: Move builds into dedicated directory

.github/workflows/main.yml, py2many/cli.py, revive.toml, tests/test_cli.py, tests/test_unsupported.py
=> tests: Replace golint with revive 

py2many/inference.py
Earlier code introduced the concept, but didn't propagate lifetime via
static analysis. This code enables PRs like #327 to move forward. Not just
for strings, but anything with a static lifetime.
TODO: propagate lifetimes for sets/lists just like dicts
=> py2many: propagate lifetimes

pyrs/transpiler.py, tests/cases/dict.py, tests/expected/dict.dart, tests/expected/dict.jl, tests/expected/dict.rs, tests/expected/nested_dict.rs
This includes a 'subset' of https://github.com/adsharma/py2many/pull/251 , and gets my project back onto the mainline of py2many.
=> pyrs: Handle indexing HashMap

py2many/cli.py, py2many/clike.py, py2many/exceptions.py, py2many/inference.py, py2many/rewriters.py, py2many/tracer.py, pycpp/transpiler.py, pydart/transpiler.py, pygo/transpiler.py, pyrs/inference.py, pyrs/transpiler.py, tests/test_transpile_self.py
Related to https://github.com/adsharma/py2many/issues/291
=> Add AstNotImplementedError

py2many/cli.py, pyjl/transpiler.py, tests/test_transpile_self.py
Improve wrapper around format.jl and fix Julia default type.
=> Julia fixes

pyrs/transpiler.py, tests/expected/sealed.rs
Fixes https://github.com/adsharma/py2many/issues/341
=> rust: fix clippy error on sealed.rs

py2many/cli.py, py2many/clike.py, py2many/rewriters.py, pycpp/tests/test_transpiler.py, pycpp/transpiler.py, pydart/plugins.py, pydart/transpiler.py, pygo/plugins.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/plugins.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/test_cli.py, tests/test_unsupported.py
=> Finish moving dispatch to plugins

py2many/inference.py, pyjl/transpiler.py, tests/cases/complex.py, tests/expected/complex.jl, tests/expected/complex.py, tests/test_cli.py
Fixes: https://github.com/adsharma/py2many/issues/379
=> python: allow complex binop int/float

.github/workflows/main.yml, pygo/transpiler.py, tests/dir_cases/test1-cpp-expected/bar.cpp, tests/dir_cases/test1-cpp-expected/baz.cpp, tests/dir_cases/test1-cpp-expected/foo.cpp, tests/dir_cases/test1-dart-expected/bar.dart, tests/dir_cases/test1-dart-expected/baz.dart, tests/dir_cases/test1-dart-expected/foo.dart, tests/dir_cases/test1-go-expected/bar.go, tests/dir_cases/test1-go-expected/baz.go, tests/dir_cases/test1-go-expected/foo.go, tests/dir_cases/test1-julia-expected/bar.jl, tests/dir_cases/test1-julia-expected/baz.jl, tests/dir_cases/test1-julia-expected/foo.jl, tests/dir_cases/test1-kotlin-expected/bar.kt, tests/dir_cases/test1-kotlin-expected/baz.kt, tests/dir_cases/test1-kotlin-expected/foo.kt, tests/dir_cases/test1-nim-expected/bar.nim, tests/dir_cases/test1-nim-expected/baz.nim, tests/dir_cases/test1-nim-expected/foo.nim, tests/dir_cases/test1-python-expected/bar.py, tests/dir_cases/test1-python-expected/baz.py, tests/dir_cases/test1-python-expected/foo.py, tests/dir_cases/test1-rust-expected/bar.rs, tests/dir_cases/test1-rust-expected/baz.rs, tests/dir_cases/test1-rust-expected/foo.rs, tests/dir_cases/test1/bar.py, tests/dir_cases/test1/baz.py, tests/dir_cases/test1/foo.py, tests/test_cli.py
Related to: https://github.com/adsharma/py2many/issues/391
=> tests: add a test for directory mode

py2many/clike.py, tests/test_transpile_self.py
Previously only `from typing import ..` was supported.
=> Allow import typing

Cargo.toml, tests/cases/import_tests.py, tests/expected/import_tests.cpp, tests/expected/import_tests.dart, tests/expected/import_tests.go, tests/expected/import_tests.jl, tests/expected/import_tests.kt, tests/expected/import_tests.nim, tests/expected/import_tests.py, tests/expected/import_tests.rs
test that import typing; typing.List style of usage works.
=> tests: add an import test

py2many/cli.py
Intoduces --force and --suffix flags
```
$ ./py2many.py --python=1 /tmp/foo.py
Writing to: /tmp
Refusing to overwrite /tmp/foo.py. Use --force to overwrite
$ ./py2many.py --python=1 --force /tmp/foo.py
Writing to: /tmp
/tmp/foo.py ... /tmp/foo.py
$ ./py2many.py --python=1 --suffix=py3 /tmp/foo.py
Writing to: /tmp
/tmp/foo.py ... /tmp/foo.py3
```
Fixes: https://github.com/adsharma/py2many/issues/355
=> cli: add some safety around overwriting original source

Cargo.toml, pyrs/transpiler.py, tests/cases/loop.py, tests/expected/loop.cpp, tests/expected/loop.dart, tests/expected/loop.go, tests/expected/loop.jl, tests/expected/loop.kt, tests/expected/loop.nim, tests/expected/loop.py, tests/expected/loop.rs
Rust complains about `while true`, requires `loop { .. }`.
=> pyrs: Fix while True

pykt/transpiler.py
Fixes https://github.com/adsharma/py2many/issues/393
=> pykt: Add missing .body_vars

pycpp/transpiler.py, pydart/transpiler.py, pyjl/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/expected/binit.dart, tests/expected/bitops.cpp, tests/expected/bubble_sort.dart, tests/expected/comb_sort.dart, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/global.dart, tests/expected/import_tests.cpp, tests/expected/nested_dict.cpp
Related to https://github.com/adsharma/py2many/issues/410
=> Simplify assign one

py2many/astx.py, py2many/cli.py, py2many/context.py, pydart/transpiler.py, tests/expected/binit.dart, tests/expected/bubble_sort.dart, tests/expected/comb_sort.dart, tests/expected/coverage.dart, tests/expected/dict.dart, tests/expected/import_tests.dart, tests/expected/nested_dict.dart, tests/expected/sys_argv.dart
The left hand side (lhs) and right hand side (rhs) need different
treatment in the transpiler. Having this info handy would help 
with cases discussed in
https://github.com/adsharma/py2many/pull/294
=> context: add a transformer to annotate lhs

.github/workflows/main.yml, py2many/analysis.py, py2many/cli.py, py2many/smt.py, pysmt/clike.py, pysmt/inference.py, pysmt/plugins.py, pysmt/transpiler.py, tests/.cljstyle, tests/cases/demorgan.py, tests/dir_cases/test1-smt-expected/bar.smt, tests/dir_cases/test1-smt-expected/baz.smt, tests/dir_cases/test1-smt-expected/foo.smt, tests/expected/demorgan.smt, tests/test_cli.py, tests/test_transpile_self.py
For more information on the language:
https://rise4fun.com/z3/tutorial
=> smt: new language

.github/workflows/main.yml
This loses some flexibility but is faster and more stable.
=> v: switch to weekly releases

.github/workflows/main.yml, pycpp/transpiler.py, tests/expected/binit.cpp, tests/expected/bubble_sort.cpp, tests/expected/comb_sort.cpp
Fixes https://github.com/adsharma/py2many/issues/161
=> cpp: pass containers by reference

py2many/declaration_extractor.py, pysmt/transpiler.py, tests/cases/datatypes.py, tests/expected/datatypes.smt
More context: A better SMT language (https://bit.ly/3AAZTR2)
Tested via: z3 -smt2 tests/expected/datatypes.smt
=> smt:  support data types

docker/Dockerfile
This uses archlinux and setsup core packages for most languages.
=> docker: add an initial Dockerfile

py2many/cli.py
Tested via:
```
cat tests/cases/equations.py | ./py2many.py --smt=1 | z3 -smt2 -in
```
=> cli: support pipes

pycpp/plugins.py, pydart/plugins.py, pygo/plugins.py, pyjl/plugins.py, pykt/plugins.py, pynim/plugins.py, pyrs/plugins.py, pyv/plugins.py, tests/cases/built_ins.py, tests/expected/built_ins.cpp, tests/expected/built_ins.dart, tests/expected/built_ins.go, tests/expected/built_ins.jl, tests/expected/built_ins.kt, tests/expected/built_ins.nim, tests/expected/built_ins.py, tests/expected/built_ins.rs, tests/expected/built_ins.v
Fixes https://github.com/adsharma/py2many/issues/395
=> builtins: handle zero argument case

.github/workflows/main.yml, tests/cases/fib_with_argparse.py, tests/expected/comment_unsupported.dart, tests/expected/coverage.dart, tests/expected/fib_with_argparse.py, tests/expected/fib_with_argparse.rs
Fixes https://github.com/adsharma/py2many/issues/461 and https://github.com/adsharma/py2many/issues/462 and https://github.com/adsharma/py2many/issues/465
=> main.yml: Fix CI

.github/workflows/main.yml, CONTRIBUTING.md, README.md, tests/cases/fib_with_argparse.py, tests/expected/comment_unsupported.dart, tests/expected/coverage.dart, tests/expected/fib_with_argparse.py, tests/expected/fib_with_argparse.rs, tests/test_cli.py
Sits on top of https://github.com/adsharma/py2many/pull/463
=> main.yml: Use Ubuntu focal

.github/workflows/main.yml, pyv/plugins.py, pyv/transpiler.py, tests/dir_cases/test1-vlang-expected/bar.v, tests/dir_cases/test1-vlang-expected/baz.v, tests/dir_cases/test1-vlang-expected/foo.v, tests/expected/assert.v, tests/expected/binit.v, tests/expected/bitops.v, tests/expected/bubble_sort.v, tests/expected/built_ins.v, tests/expected/byte_literals.v, tests/expected/classes.v, tests/expected/cls.v, tests/expected/comb_sort.v, tests/expected/coverage.v, tests/expected/dict.v, tests/expected/fib.v, tests/expected/hello_world.v, tests/expected/import_tests.v, tests/expected/infer.v, tests/expected/infer_ops.v, tests/expected/nested_dict.v, tests/expected/print.v, tests/expected/rect.v, tests/expected/sys_argv.v, tests/expected/sys_exit.v, tests/test_cli.py, tests/test_unsupported.py
Bumps V version to the latest.
~Needs vlang/v#13363 or a PR with the same effect, so I am leaving this as a draft until then.~
Will be unavailable until Monday's release, but should be safe to merge after that.
=> v: bump version and add initial class support

.github/workflows/main.yml, tests/test_cli.py
Closes https://github.com/py2many/py2many/issues/467
=> Use flutter 2.10.5

.github/workflows/main.yml
Closes https://github.com/py2many/py2many/issues/471
=> main.yml: Install smt dependencies

.github/workflows/main.yml, py2many/cli.py, tests/test_unsupported.py
=> Find format.jl at runtime

Cargo.toml, pydart/plugins.py, pygo/plugins.py, pykt/plugins.py, pynim/plugins.py, pyrs/plugins.py, pyrs/transpiler.py, pyv/inference.py, pyv/plugins.py, tests/cases/built_ins.py, tests/expected/built_ins.cpp, tests/expected/built_ins.dart, tests/expected/built_ins.go, tests/expected/built_ins.jl, tests/expected/built_ins.kt, tests/expected/built_ins.nim, tests/expected/built_ins.py, tests/expected/built_ins.rs, tests/expected/built_ins.v, tests/expected/comb_sort.v, tests/expected/infer_ops.v, tests/test_unsupported.py
=> Add float() on Dart, Go, Kotlin, Nim and V

.editorconfig, tests/cases/demorgan.py, tests/expected/demorgan.smt
Fixes https://github.com/py2many/py2many/issues/507
=> tests: Make demorgan sat

py2many/cli.py, py2many/registry.py, pycpp/__init__.py, pydart/__init__.py, pygo/__init__.py, pyjl/__init__.py, pykt/__init__.py, pynim/__init__.py, pyrs/__init__.py, pysmt/__init__.py, pyv/__init__.py, tests/test_cli.py, tests/test_transpile_self.py
Finish making main() arg parsing dynamic.
=> Move transpiler settings to respective packages

py2many/cli.py, py2many/registry.py, pycpp/__init__.py, pycpp/tracer.py, pydart/__init__.py, pygo/__init__.py, pyjl/__init__.py, pykt/__init__.py, pynim/__init__.py, pyrs/__init__.py, pysmt/__init__.py, pytest.ini, pyv/__init__.py, setup.py, tests/test_cli.py, tests/test_tracer_cpp.py, tests/test_transpile_self.py, tests/test_transpiler_cpp.py, tox.ini
Fixes https://github.com/py2many/py2many/issues/238
=> setup.py: Install transpilers under py2many

py2many/clike.py, pycpp/plugins.py, pycpp/transpiler.py, tests/cases/stdio.py, tests/expected/stdio.cpp, tests/expected/stdio.py
=> pycpp: misc fixes

.github/workflows/main.yml, py2many/process_helpers.py, pycpp/__init__.py, pyjl/__init__.py, setup.py, tests/test_cli.py, tests/test_transpile_self.py, tests/test_unsupported.py
Fixes https://github.com/py2many/py2many/issues/564
=> Fix support for Python 3.12

tests/expected/ifexp.jl, tests/test_transpile_self.py
Closes https://github.com/py2many/py2many/issues/339
=> tests: Dont suppress FileNotFoundError

.github/workflows/main.yml, pyrs/__init__.py, pysmt/__init__.py, tests/test_cli.py
Fixes https://github.com/py2many/py2many/issues/579 & https://github.com/py2many/py2many/issues/581
=> rust: Use nightly-2024-01-01

py2many/clike.py, pyrs/transpiler.py, tests/cases/classes.py, tests/cases/cls.py, tests/cases/coverage.py, tests/cases/smt_types.py, tests/expected/classes.py, tests/expected/cls.py, tests/expected/coverage.py, tests/expected/str_enum.rs, tests/test_cli.py
=> tests: Move smt compiler to invoker

.github/workflows/fast.yaml, .github/workflows/main.yml
The idea is to get a clear signal on a PR within 5 minutes.
We could still run the more comprehensive CI/CD periodically and open bug reports for things that are broken.
=> Assess a more streamlined CI/CD model

pytest.ini
https://docs.pytest.org/en/stable/reference/customize.html#finding-the-rootdir
=> pytest: rootdir is now computed

README.md
=> update README.md for dlang

.github/workflows/main.yml, pyd/__init__.py, tox.ini
=> [dlang] Honor args.indent

tox.ini
=> Use upstream jgo

.github/workflows/main.yml, pydart/transpiler.py, scripts/dart-setup.sh, tests/expected/int_enum.dart, tests/expected/str_enum.dart
=> Replace vnum with builtin enum

.github/workflows/main.yml, py2many/registry.py, pymojo/__init__.py, pymojo/clike.py, pymojo/inference.py, pymojo/plugins.py, pymojo/transpiler.py, setup.py, tests/dir_cases/test1-mojo-generated/bar.mojo, tests/dir_cases/test1-mojo-generated/baz.mojo, tests/dir_cases/test1-mojo-generated/foo.mojo, tests/expected/fib.mojo, tests/expected/hello_world.mojo, tests/test_cli.py
[Mojo](https://www.modular.com/mojo) is a recent language from modular.
=> Initial support for mojo

pymojo/transpiler.py
=> A few mojo fixes

pymojo/__init__.py, pymojo/clike.py, pymojo/rewriters.py, pymojo/transpiler.py, tests/expected/classes.mojo
=> mojo: get classes to work

pymojo/__init__.py, pymojo/inference.py, pymojo/plugins.py, pymojo/rewriters.py, pymojo/transpiler.py, tests/dir_cases/test1-mojo-expected/bar.mojo, tests/expected/assert.mojo, tests/expected/bubble_sort.mojo, tests/expected/classes.mojo, tests/expected/comb_sort.mojo, tests/expected/comparison.mojo, tests/expected/fib.mojo, tests/expected/rect.mojo, tests/expected/sys_exit.mojo
=> mojo: fix bubble sort

py2many/rewriters.py, pymojo/plugins.py, pymojo/transpiler.py, tests/expected/dict.mojo, tests/expected/fstring.mojo
Some of the tests have expected output updated. But may not pass right now because upstream mojo hasn't implemented the feature yet.
=> mojo: fix a few more tests

pymojo/clike.py
test plan:
```
def foo():
var = 10
return var
fn foo() -> Int:
var var_ = 10
return var_
```
=> mojo: initial list of keywords

py2many/cli.py, pyrs/transpiler.py
=> Add a --no-stict option

pycpp/clike.py, pyd/clike.py, pydart/clike.py, pygo/clike.py, pyjl/clike.py, pykt/clike.py, pymojo/clike.py, pynim/clike.py, pysmt/clike.py, pyv/clike.py
`_type_map` and friends are now class variables
=> Fixup breakages from #656

py2many/cli.py, py2many/language.py
Optional flag. Convenient when installing a formatter is tedious.
=> Ignore formatter errors

py2many/clike.py, pysmt/clike.py, pysmt/inference.py, pysmt/transpiler.py
Tested via:
```
from py2many.smt import check_sat
from typing import Tuple
def constraints(input: Tuple[Int], op: Tuple[FuncType]):
op[0](input[0], input[1]) == input[2]
def Add(i: Int, j: Int) -> Int:
return i + j
a = [1, 2, 3]
b = [Add]
assert constraints(a, b)
check_sat()
```
=> Fix some smt2 bugs

tests/expected/classes.kt, tests/expected/cls.kt, tests/expected/coverage.kt, tests/expected/infer_ops.kt, tests/expected/int_enum.kt, tests/expected/rect.kt, tests/expected/str_enum.kt
`jgo com.pinterest.ktlint:ktlint-cli --format tests/expected/*.kt`
Related to: #634
=> Run kotlin formatter

py2many/ast_helpers.py, py2many/inference.py, py2many/python_transformer.py, py2many/toposort_modules.py, setup.py, tox.ini
* Drop support for py38
* Trim astor, toposort, unittest-expander as deps
=> Trim dependencies

py2many/clike.py, py2many/inference.py, pyrs/transpiler.py
=> py2many.clike: code cleanup

py2many/python_transformer.py, pymojo/clike.py, tests/expected/bubble_sort.mojo, tests/expected/fstring.mojo, tests/expected/fstring.py
=> Test fixes

pysmt/transpiler.py, tests/cases/datatypes_base.py, tests/dir_cases/test1-smt-expected/bar.smt, tests/dir_cases/test1-smt-expected/baz.smt, tests/expected/datatypes_base.smt, tests/expected/smt_types.smt
=> smt2: fix tests

py2many/clike.py, py2many/result.py, pyrs/inference.py, pyrs/plugins.py, pyrs/transpiler.py, tests/cases/hello-wuffs.py
=> rust: improve hello-wuffs.py example

tests/cases/hello-wuffs.py
=> wuffs: make the test pass

tests/cases/hello-wuffs.py
=> wuffs: fix a bug in the test

pyrs/__init__.py
=> rust: fix hello_world-rust

.pre-commit-config.yaml
So you don't forget to run `black/flake8/isort`
=> [ci] pre-commit hooks

pyzig/plugins.py, pyzig/transpiler.py
TBD: parse result types correctly and insert try conditionally.
=> zig: improve loops

py2many/cli.py, py2many/clike.py, pyzig/plugins.py, pyzig/transpiler.py, tests/expected/fib.zig, tests/expected/hello_world.zig, tests/expected/loop.zig
```
const print = std.debug.print;
```
is a common zig idiom.
=> Zig aliases

py2many/smt.py, pysmt/__init__.py, pysmt/rewriters.py, pysmt/transpiler.py, tests/cases/equations.py, tests/expected/equations.smt
=> smt: fix test inputs to be valid python

py2many/inference.py, tests/expected/equations.smt
Also fix a deprecation warning
=> smt: fix failing test

py2many/clike.py, py2many/inference.py, pygo/inference.py, pyjl/inference.py, pykt/inference.py, pymojo/inference.py, pynim/inference.py, pyrs/inference.py, pysmt/inference.py, pysmt/transpiler.py, pyv/inference.py, pyzig/inference.py, tests/expected/equations.smt
Most of this refactor was done by an AI with some human prompting.
The commit is in the right direction (reduces copy-pasta). But doesn't pass all the tests yet.
=> [AI refactor]: move common code to py2many/inference.py

.pre-commit-config.yaml
___.pre-commit-config.yaml___
```yaml
-   repo: https://github.com/cpplint/cpplint
rev: 2.0.0
hooks:
- id: cpplint
args:
- --filter=-legal/copyright,-whitespace/semicolon,-runtime/reference
- tests/expected/*.cpp
```
=> Add cpplint to pre-commit

py2many/python_transformer.py, py2many/registry.py
=> python: honor --no-prologue

pysmt/clike.py, pysmt/inference.py, tests/cases/equations.py, tests/expected/equations.smt
```
cat tests/cases/equations.py | ./py2many.py --smt=1 | z3 -smt2 -in
sat
((x 7)
(y 0)
(z (- (/ 69.0 100.0))))
```
=> smt: support float/real

docker/Dockerfile, pymojo/transpiler.py, tests/expected/bubble_sort.mojo, tests/expected/classes.mojo, tests/expected/cls.mojo
* Create a new dev environment based on [getting started](https://docs.modular.com/mojo/manual/get-started/)
* Update tests to match recent versions of mojo
=> Mojo fixes

README.md
=> Update README for better visibility

py2many/inference.py, py2many/rewriters.py, pycpp/transpiler.py
=> Fix deprecation warnings

pysmt/__init__.py, pysmt/rewriters.py, pysmt/transpiler.py, tests/cases/equations.py, tests/cases/triangle_buggy.py, tests/expected/equations.smt, tests/expected/triangle_buggy.smt
=> pysmt: fix the buggy triangle classifier with counter example

scripts/zig-runner.sh, scripts/zig-setup.sh, tests/test_cli.py
Tested to support importing pylib
=> Fix setup/runner for zig
