py2many/py2many

tests/expected/binit.jl, tests/expected/fib.jl, tests/expected/print.jl, tests/test_cli.py
Add a compiler, so we can detect out of sync expected outputs
=> julia: unmask test failures

py14/tests/test_context.py, py14/transpiler.py, py2many/analysis.py, py2many/clike.py, py2many/context.py, py2many/inference.py, pyrs/tests/test_context.py, pyrs/transpiler.py, tests/expected/binit.rs, tests/expected/fib.cpp, tests/expected/fib.dart, tests/expected/fib.go, tests/expected/fib.rs, tests/expected/infer_ops.cpp, tests/expected/infer_ops.dart, tests/expected/infer_ops.go, tests/expected/infer_ops.rs
Rust expects vector indices to be `usize`.
Tested via:
```
from ctypes import c_int32
def bar() -> c_int32:
return c_int32(2)
def main():
d = [1, 2, 3]
i: c_int32 = 2
d[i] = 4
d[bar()] += 1
```
Generates:
```
fn bar() -> i32 {
return c_int32(2);
}
fn main() {
let d = vec![1, 2, 3];
let i: i32 = 2;
d[i as usize] = 4;
d[bar() as usize] += 1;
}
```
=> rust: infer list index type and widen if necessary

py14/transpiler.py, py2many/clike.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/clike.py, pynim/transpiler.py, pyrs/clike.py, pyrs/transpiler.py, tests/cases/binit.py, tests/expected/binit.cpp, tests/expected/binit.dart, tests/expected/binit.go, tests/expected/binit.jl, tests/expected/binit.kt, tests/expected/binit.nim, tests/expected/binit.rs
This gets us the exactly once translation from python types
to target language types
Also add type annotations to binit.py to help rust understand
that high is a i32
=> backends: use _typename_from_annotation

py2many/cli.py, pyrs/transpiler.py, tests/expected/binit.rs, tests/expected/global.rs, tests/test_cli.py
Inserts a dereference precisely where it's needed
Fixes https://github.com/adsharma/py2many/issues/19
=> rust: RustLoopIndexRewriter

py2many/cli.py, pyrs/clike.py, pyrs/declaration_extractor.py, pyrs/inference.py, pyrs/transpiler.py, tests/expected/binit.rs, tests/expected/infer_ops.rs, tests/test_cli.py
Fixes compile errors and some semantic errors. More work needed
for cases like:
```
fn add1(x: i8, y: i8) -> i16 {
-    return (x + y) as i16;
+    return (x as i16 + y as i16);
}
```
so add1(127, 10) returns 137 instead of -119.
Related to https://github.com/adsharma/py2many/issues/16
=> rust: add rust specific type inference

py2many/cli.py, tests/test_cli.py
Add overrides for two errors occurring due
to the input code.
=> tests: Lint C++ using -Wall -Werror

py2many/cli.py, py2many/rewriters.py, pyrs/transpiler.py, tests/cases/fstring.py, tests/expected/fstring.rs
This handles python's joined strings as follows:
print(f"hello world: {a+1} number")
becomes
println!("{}","".join(vec!["hello world: ", String::from((a + 1)), " number"]););
All we need to do now is to transpile "".join(...) in the target language,
which we need to do anyway because of how popular that construct is in
python code.
Related to: https://github.com/adsharma/py2many/issues/74
=> rewriters: FStringJoinRewriter

py2many/cli.py, py2many/rewriters.py, tests/cases/rect.py, tests/test_unsupported.py
This allows us to consume the rest of the test. The comment
can be generated from the ast node in the target language in
a future diff
Related to: https://github.com/adsharma/py2many/issues/7
=> rewriter: move docstrings to a AST node comment field

.github/workflows/main.yml, tests/test_cli.py, tox.ini
May be useful for testing performance with or without checks.
Also make some of these knobs accessible from cmdline args as
well as env.
Tested via:
PYTHONPATH=. python3 tests/test_cli.py  -k go -v
PYTHONPATH=. python3 tests/test_cli.py --lint -k go -v
=> tests: make lint configurable

py2many/cli.py, py2many/inference.py, pydart/clike.py, pydart/transpiler.py, tests/expected/infer_ops.dart, tests/test_cli.py
Also rerun type inference after the post_rewriters are done.
Fixes: https://github.com/adsharma/py2many/issues/199
=> dart: handle integer division in the rewriter

py2many/inference.py, pyrs/inference.py, pyrs/transpiler.py, tests/cases/langcomp_bench.py, tests/expected/binit.cpp, tests/expected/binit.dart, tests/expected/binit.go, tests/expected/binit.kt, tests/expected/binit.rs, tests/expected/langcomp_bench.rs
This is where rustc -O is 100x faster and serves to showcase
potential perf gains.
However, there was a little problem with type inference for
total += array[i]
where lhs is f64 and rhs is i32, needing a cast.
=> rust: add the langcomp benchmark test case

pyrs/transpiler.py, tests/expected/assert.rs, tests/expected/asyncio_test.rs, tests/expected/binit.rs, tests/expected/bubble_sort.rs, tests/expected/comb_sort.rs, tests/expected/coverage.rs, tests/expected/fib.rs, tests/expected/fstring.rs, tests/expected/global.rs, tests/expected/global2.rs, tests/expected/hello_world.rs, tests/expected/infer.rs, tests/expected/infer_ops.rs, tests/expected/int_enum.rs, tests/expected/lambda.rs, tests/expected/langcomp_bench.rs, tests/expected/print.rs, tests/expected/rect.rs, tests/expected/str_enum.rs, tests/test_cli.py
This allows us to specify edition for async programs.
Fixes https://github.com/adsharma/py2many/issues/198
=> rust: use inline cargo.toml instead of cargo-deps

.github/workflows/main.yml, py14/transpiler.py, py2many/cli.py, tests/expected/bubble_sort.cpp, tests/expected/comb_sort.cpp, tests/test_cli.py, tests/test_unsupported.py, tox.ini
Adds plumbing for using with g++ only, testing with astyle as
an alternative formatter.
Also allow CLANG_FORMAT_STYLE to determine the clang-format
style to be used.
=> cli: Support CXX and CXXFLAGS

py2many/cli.py
pypi package errors out because of env=None.
=> cli: make pypi package work again

py2many/analysis.py, py2many/cli.py, py2many/clike.py, pyrs/transpiler.py, tests/test_unsupported.py
This was tested with:
```
def sum_as_string(a: int, b: int) -> int:
return a + b
```
py2many --rust=1 --extension=1 /tmp/foo.py
and by copying over foo.rs as src/lib.rs in a pyO3 example template.
Related to: https://github.com/adsharma/py2many/issues/62
=> rust: support pyO3 extensions

py2many/cli.py, pyrs/inference.py, pyrs/transpiler.py
This covers the mechanics of using PyResult from an extension.
Tested via the canonical pyO3 example:
```
def sum_as_string(a: int, b: int) -> str:
return str(a + b)
```
Related to: https://github.com/adsharma/py2many/issues/62
=> rust: handle strings as return types

py2many/clike.py, py2many/declaration_extractor.py, pycpp/clike.py, pydart/clike.py, pygo/inference.py, pyjl/clike.py, pykt/inference.py, pynim/inference.py, pyrs/inference.py
Using strings in language specific type maps has the problem that it
doesn't cover the case where the type has been imported using an alias.
This is a step towards handling that correctly, although more work needs
to be done. We still have checks against FIXED_WIDTH_INTS_NAME in a few
places
=> inference: use classes in type_map

.github/workflows/main.yml, py2many/clike.py, py2many/declaration_extractor.py, pyrs/plugins.py, pyrs/transpiler.py, setup.py, tests/cases/fib_with_argparse.py, tests/expected/fib_with_argparse.rs, tox.ini
This allows us to keep complex use cases such as argument parsing
separate from the core transpiler.
Related to: https://github.com/adsharma/py2many/issues/179
=> rust: implement plugin based code generation

pyrs/plugins.py, pyrs/transpiler.py, tests/cases/with_open.py
Introduces a companion library: pylib. This could be a submodule.
Gets us closer to with_open.py example in CI
Introduces a few new concepts:
MODULE_DISPATCH_TABLE - this is where you map module names (tempfile.xxx)
DECORATOR_DISPATCH_TABLE - tells the transpiler what the decorator is doing
FUNCTION_DISPATCH_TABLE - looked up on attributes as well as func dispatch
=> rust: improve plugin system for file IO

py2many/clike.py, tests/cases/coverage.py, tests/expected/coverage.cpp, tests/expected/coverage.dart, tests/expected/coverage.go, tests/expected/coverage.jl, tests/expected/coverage.kt, tests/expected/coverage.nim, tests/expected/coverage.rs
Fixes: https://github.com/adsharma/py2many/issues/247
=> py2many: escape quotes in strings

py2many/clike.py, py2many/inference.py, pyrs/clike.py, pyrs/transpiler.py, tests/expected/coverage.rs, tests/expected/global.rs, tests/expected/global2.rs, tests/expected/infer_ops.rs
Add an optional attribute to node.annotation. Targets that care
about it (such as rust in this diff and cpp and others in the future)
can specialize the types further.
=> rust: implement basic lifetimes for strings

py2many/clike.py, pyrs/transpiler.py, tests/test_transpile_self.py
Tested with:
```
from dataclasses import dataclass
def foo() -> "Point":
return bar()
def bar() -> "Point":
return Point(1, 2)
@dataclass
class Point:
x: int
y: int
if __name__ == '__main__':
print(foo().x)
```
Fixes: https://github.com/adsharma/py2many/issues/277
=> py2many: handle funcs accessed out of order

py2many/clike.py, py2many/declaration_extractor.py, py2many/inference.py, pyrs/clike.py, pyrs/inference.py, pyrs/transpiler.py, tests/test_unsupported.py
Tested with:
```
class Foo:
A = 1
B = 2
def foo(self):
self._c = 3
```
=> rust: handle classes with class/member variables

pyrs/transpiler.py
Tested with:
```
a: List[int] = [3] * 10
=>
let a: Vec<i32> = vec![10; 3];
```
=> rust: handle vec initialization correctly

py2many/cli.py, py2many/clike.py, py2many/context.py, py2many/toposort_modules.py, py2many/tracer.py, pycpp/tests/test_analysis.py, pycpp/tests/test_context.py, pycpp/tests/test_scope.py, pycpp/tests/test_tracer.py, pycpp/transpiler.py, pyrs/tests/test_analysis.py, pyrs/tests/test_context.py, pyrs/tests/test_scope.py, pyrs/tests/test_tracer.py, setup.py, tests/test_transpile_self.py, tox.ini
Passes the test case below. bar1() defined in another
file is correctly inferred as returning an int.
Tested via: py2many --rust=1 /tmp/testdir
containing the two files in the paste attached to the issue
Related: https://github.com/adsharma/py2many/issues/158
=> py2many: cross module type inference

py2many/cli.py, py2many/exceptions.py, py2many/inference.py, tests/test_cli.py, tests/test_transpile_self.py, tests/test_unsupported.py
This also shows why the transpilers should not use TypeError.  As predicted, that causes real exceptions to not be noticed.
=> Fix and refine test_error_cases

py2many/clike.py, tox.ini
AttributeError occurs because node.module is None
when `from . import ...`
=> visit_ImportFrom fix and NamedExpr not implemented

pyrs/transpiler.py, tests/expected/bubble_sort.rs, tests/expected/cls.rs, tests/expected/comb_sort.rs, tests/expected/coverage.rs, tests/expected/fib_with_argparse.rs, tests/expected/sealed.rs, tests/expected/with_open.rs
Steps before we consolidate the special casing by type into fewer
code paths. Probably move some of the logic around lazy static
out of the function.
Starting with rust because it has the largest assign one func.
Related to: https://github.com/adsharma/py2many/issues/410
=> rust: streamline assign one

py2many/rewriters.py, py2many/scope.py, pycpp/transpiler.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, tests/expected/comb_sort.py
We need to search the scopes in reverse order. It exposed a second
bug. Which is that a variable defined in the outer scope is redefined
in the current scope according to the current logic in visit_Assign_one.
Fix the logic to define it only if it hasn't been defined before.
Fixes: https://github.com/adsharma/py2many/issues/417
=> analysis: fix the order of lookup

.github/workflows/main.yml
It seems that while pinning V version to a specific commit, I have not considered the fact that the V's Makefile always fetching latest v.c could break bootstrapping. This PR addresses that by also pinning the version of v.c.
I know this is not ideal, I'll work on getting up-to-date, pre-built builds but in the mean time the CI should not fail for others.
=> v: pin vc to fix CI issue

py2many/clike.py, pycpp/clike.py, pycpp/transpiler.py, pydart/clike.py, pydart/transpiler.py, pygo/clike.py, pygo/transpiler.py, pyjl/clike.py, pyjl/transpiler.py, pykt/clike.py, pykt/transpiler.py, pynim/clike.py, pynim/transpiler.py, pyrs/clike.py, pyrs/transpiler.py, pyv/transpiler.py
```
sed -i '/^class.*Transpiler/,$s/^\(.*visit\)\([^>]*\):$/\1\2 -> str:/' */transpiler.py */clike.py
```
and then removed anything that caused extra type errors. Mostly visit_arg() which returns a tuple
=> typing: add annotations

.github/workflows/main.yml
When I first started working on the V PR, I was confused on why the CI didn't run on my branch. The main only setup is unusual and not exactly optimal in my opinion. It forces people to either do work only on the main branch, make a PR to the main branch in this repo or manually run the workflows everytime.
=> ci: Run CI on all branches

Cargo.toml, py2many/inference.py, pyrs/transpiler.py, tests/cases/classes.py, tests/expected/classes.cpp, tests/expected/classes.dart, tests/expected/classes.go, tests/expected/classes.jl, tests/expected/classes.kt, tests/expected/classes.py, tests/expected/classes.rs
Allows classes.py to pass on many targets
Related to: https://github.com/adsharma/py2many/issues/400
=> py2many: Fix type inference for methods

py2many/cli.py, pysmt/transpiler.py, tests/cases/equations.py, tests/expected/equations.smt
- write info to stderr instead of stdout
- handle tuple transpilation
- use get-value instead of get-model in tests
Tested via:
cat tests/cases/equations.py | ./py2many.py --smt=1 - | z3 -smt2 -in
=> smt: cleanup pipe based usage

py2many/cli.py, py2many/clike.py, py2many/language.py, pycpp/transpiler.py, pydart/transpiler.py, pygo/transpiler.py, pyjl/transpiler.py, pykt/transpiler.py, pynim/transpiler.py, pyrs/transpiler.py, pysmt/transpiler.py, pyv/transpiler.py, tests/test_cli.py, tests/test_transpile_self.py
This allows directory mode transpilation to create a Cargo.toml
via cargo new --bin.
Any relative imports are transpiled to `mod name` instead of
`extern create name`.
Tested via:
```
head /tmp/foo/*.py
==> /tmp/foo/foo1.py <==
def foo1():
return 42
==> /tmp/foo/main.py <==
from .foo1 import foo1
def main():
print(foo1())
py2many --rust=1 /tmp/foo --outdir /tmp/rustfoo
cd /tmp/rustfoo
cargo run
42
```
Related to: https://github.com/adsharma/py2many/issues/408
=> rust: use cargo new

.github/workflows/main.yml
Kotlin on macos had to be removed in https://github.com/py2many/py2many/pull/468 ; solution now found
=> main.yml: Reable Kotlin on macos

py2many/cli.py, py2many/rewriters.py, py2many/tracer.py, tests/cases/loop.py, tests/expected/loop.cpp, tests/expected/loop.dart, tests/expected/loop.go, tests/expected/loop.jl, tests/expected/loop.kt, tests/expected/loop.nim, tests/expected/loop.py, tests/expected/loop.rs
This aims to remove the redundant code produced by the initial indexing translation mechanism. This includes redundant operations, such as `-1+1`. This is a proposed fix for #529.
Furthermore, it also introduces some heuristics to translate negative indexing to Julia.
=> Improve indexing translation

Cargo.toml, py2many/context.py, tests/cases/ifexp.py, tests/expected/ifexp.cpp, tests/expected/ifexp.nim, tests/expected/ifexp.py, tests/expected/ifexp.rs
Without this, some assignment statements are not properly annotated with variable context (e.g. which variables are assigned inside the body).
We were hitting this case after a rewrite.
Fixes: https://github.com/py2many/py2many/issues/527
=> Add missing generic_visit()

.github/workflows/main.yml, CONTRIBUTING.md, tests/test_cli.py, tox.ini
Following on from https://github.com/py2many/py2many/pull/539 , jgo is now used for kscript also, which means Windows can now also easily run the Kotlin tests.
Kotlin still needs to be installed, and `KOTLIN_HOME` needs to be set.  https://github.com/scijava/jgo/issues/89 is the issue for running kotlin directly from jgo without it being installed first.
=> Use jgo for kscript

pyrs/__init__.py
CI/CD continues to run with a specific rustup nightly. Fixes #594
=> Allow any rust toolchain developer prefers

.github/workflows/main.yml, docker/Dockerfile, pysmt/__init__.py, scripts/cljstyle, tests/cases/demorgan.py, tests/expected/demorgan.smt
Related to #508 
z3 has a somewhat counter intuitive interface, which is reflected in z3py [examples](https://ericpony.github.io/z3py-tutorial/guide-examples.htm).
In order to prove `something`, they construct a test case for `!something` and verify that it's `unsat`.
=> Restore z3/smt behavior to be the same as z3py

py2many/clike.py, pyrs/clike.py, pyrs/inference.py, pyrs/transpiler.py
There is a long standing code duplication issue:
py$lang/inference.py uses `get_id(node.annotation)` to infer types.
py$lang/transpiler.py uses ` _typename_from_annotation(node)` to infer types.
The latter is more powerful and should be used in `inference.py` as well. However, due to a circular dependency, inference.py can't use `_typename_from_annotation`. One way to resolve it by organizing type inference code into a sequence of classmethods.
This PR does it only for rust. If it passes tests, we could repeat it for all other targets and then fix up `inference.py` to use the more comprehensive method.
=> Make _typename_from_annotation a classmethod

tests/test_cli.py, tests/test_unsupported.py, tox.ini
This unlocks the capability to run a specific test for a specific language:
```
pytest -k bubble_sort-rust
```
=> Remove dependency on unitest and unittest_expander

py2many/inference.py
=> py2many: fix type inference for list slices

py2many/scope.py, py2many/tracer.py
Previously we were not adding lambdas to the parent scopes.
Doing so is necessary for type inference of lambda arguments.
Related to: #622
=> py2many: add lambda to scopes for type inference
